---
- name: upload cloud-init snippet
  import_playbook: snippet.yml
  tags: cloud-init

- name: create vm golden image template
  import_playbook: virtual-machine.yml
  tags: vm-golden-image

- name: create ct golden image template
  import_playbook: linux-container.yml
  tags: ct-golden-image
