---
- hosts: hypervisors
  gather_facts: false
  vars_files:
    - ../vars/secrets.yml

  tasks:
    - name: install cloud init package
      apt:
        name: cloud-init
        state: latest
      register: cloudinit_installed

    - name: Enable snippets on local storage
      command:
        cmd: pvesm set local --content iso,vztmpl,snippets
      changed_when: true

    - name: Upload cloud-init config
      template:
        src: "{{ playbook_dir }}/../templates/cloud-init.yml.j2"
        dest: /var/lib/vz/snippets/cloud-init.yml
        mode: '0644'
      register: template_uploaded

    - name: validate cloud-init config
      command:
        cmd: cloud-init schema --config-file /var/lib/vz/snippets/cloud-init.yml --annotate
      when: cloudinit_installed is success and template_uploaded is success
      changed_when: false
      register: cloudinit_validated
      failed_when: cloudinit_validated.rc != 0
